### ISSUE TITLE
could not acquire lock on 0x7fff0000 on windows 10

### ISSUE THREAD

**Issue by ericurse** [awnumar/memcall#3]
<memcall> could not acquire lock on 0x7fff0000, limit reached? [Err: Insufficient quota to complete the requested service.]

how to fix this problem?

**Comment by awnumar** [comment]
See the `Remarks` section in the `VirtualLock` documentation: https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtuallock

This issue is due to the process using up its quota for locking things into memory. The quota may be increased with `SetProcessWorkingSetSize`: https://docs.microsoft.com/en-gb/windows/win32/api/winbase/nf-winbase-setprocessworkingsetsize

However it doesn't look like this system-call is available in the Go standard library here: https://pkg.go.dev/golang.org/x/sys/windows?tab=doc

I'll try to get it added soon when I have some time. For now you can try using `Enclave` objects or `Stream` objects (in [memguard](https://github.com/awnumar/memguard)) that store data in memory in encrypted form. They do not need to utilise memory locking as much.

**Comment by awnumar** [comment]
The required system calls are now available in the standard library.

**Comment by ericurse** [comment]
> The required system calls are now available in the standard library.

Still not working. 
alloc over 2GB memory...

**Comment by awnumar** [comment]
What did you do

**Comment by ericurse** [comment]
> What did you do

I am trying to program a memory stress test tool

**Comment by awnumar** [comment]
I meant what did you do to try and fix the problem. Did you change your process's working set size?

**Comment by ericurse** [comment]
> I meant what did you do to try and fix the problem. Did you change your process's working set size?

yes, i tried

**Comment by sivadath** [comment]
Faced the same issue, with latest code it got resolved. Thanks.

**Comment by awnumar** [comment]
@sivadath Do you mean using the SetProcessWorkingSetSizeEx system-call fixed the issue for you?

**Comment by sivadath** [comment]
yes

**Comment by awnumar** [comment]
@sivadath Alright. Thanks for letting me know.
